export { default as Login } from './login'
export { default as Registration } from './registration'
export { default as Home } from './home'
export { default as Leads } from './leads'
export { default as Profile } from './profile'
